"use client";
import {
  SparklesIcon,
  BoltIcon,
  UserCircleIcon,
} from "@heroicons/react/24/outline";
import { Typewriter } from "react-simple-typewriter";
import Lottie from "lottie-react";
import aiAnimation from "../../public/animations/ai.json";

export default function HomePage() {
  return (
    <main className="bg-gradient-to-b from-gray-900 via-indigo-900 to-indigo-950 text-white">
      {/* HERO SECTION */}
      <section className="min-h-screen flex flex-col items-center justify-center text-center px-6 py-32">
        <h1 className="text-5xl sm:text-6xl font-extrabold mb-6">
          Build Stunning Resumés <br />
          <span className="text-indigo-400">in Seconds with AI</span>
        </h1>
        <p className="text-lg sm:text-xl text-indigo-100 max-w-2xl mb-8">
          No sign-up needed. Just input your info and let the AI do the rest.
        </p>
        <a
          href="#generate"
          className="px-6 py-3 bg-indigo-600 hover:bg-indigo-500 rounded-xl text-white font-semibold transition"
        >
          Generate My Resume
        </a>
      </section>

      {/* AI PREVIEW */}
      <section className="relative py-32 bg-gradient-to-br from-gray-950 via-indigo-900 to-purple-900 overflow-hidden">
        <div className="absolute -top-40 left-0 w-[500px] h-[500px] bg-purple-500 opacity-10 blur-[150px] rounded-full" />
        <div className="absolute bottom-0 right-0 w-[400px] h-[400px] bg-indigo-500 opacity-10 blur-[120px] rounded-full" />

        <div className="relative z-10 max-w-5xl mx-auto px-6 text-center">
          <div className="inline-flex items-center gap-3 mb-4">
            <SparklesIcon className="h-8 w-8 text-yellow-400 animate-pulse" />
            <span className="text-yellow-300 font-medium text-lg tracking-wide uppercase">
              Watch AI Build It
            </span>
          </div>

          <h2 className="text-4xl sm:text-5xl font-bold mb-6">
            Live Resume Generation Preview
          </h2>
          <p className="max-w-2xl mx-auto text-indigo-100 text-lg mb-12">
            AI-generated summaries, experiences, and skills tailored to your
            profile.
          </p>

          {/* Lottie Animation */}
          <div className="w-44 sm:w-56 mx-auto mb-10">
            <Lottie animationData={aiAnimation} loop autoplay />
          </div>

          {/* Glass card preview */}
          <div className="backdrop-blur-lg bg-white/5 border border-white/20 rounded-2xl p-8 sm:p-12 shadow-xl text-left font-mono text-indigo-100 max-w-3xl mx-auto">
            <p className="mb-4">
              <span className="text-yellow-300 font-semibold">Summary:</span>{" "}
              <Typewriter
                words={[
                  "Creative Software Engineer with expertise in React and backend architecture.",
                  "UX-focused Designer passionate about clean, user-friendly interfaces.",
                  "Data Scientist skilled in predictive modeling and Python scripting.",
                ]}
                loop={0}
                cursor
                cursorStyle="_"
                typeSpeed={45}
                deleteSpeed={30}
                delaySpeed={2500}
              />
            </p>
            <p className="mt-6">
              <span className="text-yellow-300 font-semibold">Experience:</span>
              <br />• Engineer @ TechCorp (2021–2023)
              <br />• Intern @ DevHub (2020–2021)
            </p>
          </div>
        </div>
      </section>
      {/* FEATURES */}
      <section className="py-32 px-6 bg-gray-950 text-white">
        <div className="max-w-6xl mx-auto text-center">
          <h2 className="text-4xl sm:text-5xl font-bold mb-12">
            Why Choose This Resume Builder?
          </h2>
          <div className="grid gap-12 sm:grid-cols-3 text-left">
            <div className="flex flex-col items-start">
              <BoltIcon className="h-8 w-8 text-indigo-400 mb-4" />
              <h3 className="text-xl font-semibold mb-2">Instant Results</h3>
              <p className="text-indigo-100">
                Get a polished resume generated by AI in seconds. No editing
                hassle.
              </p>
            </div>
            <div className="flex flex-col items-start">
              <UserCircleIcon className="h-8 w-8 text-indigo-400 mb-4" />
              <h3 className="text-xl font-semibold mb-2">No Account Needed</h3>
              <p className="text-indigo-100">
                Start building right away — no sign-up, no email, no nonsense.
              </p>
            </div>
            <div className="flex flex-col items-start">
              <SparklesIcon className="h-8 w-8 text-indigo-400 mb-4" />
              <h3 className="text-xl font-semibold mb-2">Powered by AI</h3>
              <p className="text-indigo-100">
                Our AI understands your input and writes real, tailored resume
                content.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CALL TO ACTION */}
      <section id="generate" className="bg-indigo-950 py-28 text-center">
        <h2 className="text-4xl font-bold mb-6">Ready to Create Yours?</h2>
        <p className="text-indigo-200 mb-8 text-lg">
          It’s fast, free, and surprisingly smart.
        </p>
        <a
          href="/resume-builder"
          className="px-6 py-3 bg-yellow-400 hover:bg-yellow-300 text-indigo-900 font-bold rounded-xl transition"
        >
          Launch Resume Builder
        </a>
      </section>

      {/* FOOTER */}
      <footer className="bg-gray-950 text-center text-sm text-indigo-300 py-10">
        © {new Date().getFullYear()} AI Resume Builder by Christian Rey
        Villablanca. No sign-up. Just results.
      </footer>
    </main>
  );
}
